# Generated by CoffeeScript 1.7.1
define ["jquery"], ($) ->
  class SharePointAppPartResizer
    SharePointAppPartResizer=(id)->
      @init(id)
    @senderId = ""
    init:(id)  ->
      params = document.URL.split("?")[1].split("&")
      i = 0
      while i < params.length
        param = params[i].split("=")
        @senderId = decodeURIComponent(param[1]).replace("#", "")  if param[0].toLowerCase() is "senderid"
        i = i + 1
      @adjustSize(id)
      return

    adjustSize :(id) ->
      width = $("body").width()
      height = $("##{id}").height() + $("#contentRow").css("padding-top").replace("px", "") * 1 + $("#contentRow").css("padding-bottom").replace("px", "") * 1
      resizeMessage = "<message senderId=" + @senderId + ">resize(" + width + "," + height + ")</message>"
      window.parent.postMessage resizeMessage, "*"
      return
SharePointAppPartResizer
