# Generated by CoffeeScript 1.7.1
  define ["jquery"], ($) ->
    SharePointAppPartResizer = ->
      SharePointAppPartResizer = ->
        @init()
        return
      SharePointAppPartResizer::senderId = ""
      SharePointAppPartResizer::init = ->
        i = undefined
        param = undefined
        params = undefined
        params = document.URL.split("?")[1].split("&")
        i = 0
        while i < params.length
          param = params[i].split("=")
          @senderId = decodeURIComponent(param[1]).replace("#", "")  if param[0].toLowerCase() is "senderid"
          i = i + 1
        @adjustSize()
        return

      SharePointAppPartResizer::adjustSize = ->
        resizeMessage = undefined
        height = undefined
        width = undefined
        width = $("body").width()
        height = $("#contentRow").height() + $("#contentRow").css("padding-top").replace("px", "") * 1 + $("#contentRow").css("padding-bottom").replace("px", "") * 1
        resizeMessage = "<message senderId=" + @senderId + ">resize(" + width + "," + height + ")</message>"
        window.parent.postMessage resizeMessage, "*"
        return

    return
    

  return


## sourceMappingURL=Rezie.map
